# Generated by Django 5.2.10 on 2026-01-23 15:21


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[str] = []

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=100, verbose_name="Место выполнения привычки")),
                ("time", models.TimeField(verbose_name="Время, когда необходимо выполнять привычку")),
                ("action", models.CharField(max_length=100, verbose_name="Выполняемое действие")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                (
                    "periodicity",
                    models.PositiveIntegerField(default=1, verbose_name="Периодичность выполнения привычки в днях"),
                ),
                ("reward", models.CharField(blank=True, max_length=100, null=True, verbose_name="Вознаграждение")),
                ("duration", models.PositiveIntegerField(verbose_name="Время на выполнение привычки в секундах")),
                ("is_public", models.BooleanField(default=False, verbose_name="Признак публичности")),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
